#!/usr/bin/env python3
"""
Simple Video-to-Action Workflow - Direct implementation without complex coordination
Processes YouTube videos and generates actionable content immediately.
"""

import json
import os
import sys
from pathlib import Path
from typing import Dict, Any, Optional
from datetime import datetime

# Import our direct action generator
from direct_action_generator import DirectActionGenerator

class SimpleVideoWorkflow:
    """Simple, direct video-to-action workflow without complex agent coordination."""
    
    def __init__(self, output_dir: str = "workflow_output"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)
        self.action_generator = DirectActionGenerator()
    
    def process_video(self, video_id: str, transcript_file: Optional[str] = None) -> Dict[str, Any]:
        """Process a single video and generate actions."""
        
        print(f"Processing video: {video_id}")
        
        # Step 1: Get transcript (from file or existing data)
        transcript = self._get_transcript(video_id, transcript_file)
        if not transcript:
            return {"error": f"No transcript found for video {video_id}"}
        
        # Step 2: Generate actions directly
        action_result = self.action_generator.generate_actions(transcript, video_id)
        
        # Step 3: Save results
        output_file = self.output_dir / f"{video_id}_simple_workflow.json"
        with open(output_file, 'w') as f:
            json.dump(action_result, f, indent=2)
        
        print(f"Results saved to: {output_file}")
        
        # Step 4: Generate implementation files
        self._generate_implementation_files(video_id, action_result)
        
        return {
            "status": "success",
            "video_id": video_id,
            "actions_generated": action_result["total_actions"],
            "estimated_time": action_result["estimated_total_time"],
            "output_file": str(output_file),
            "category": action_result["category"]
        }
    
    def _get_transcript(self, video_id: str, transcript_file: Optional[str] = None) -> Optional[str]:
        """Get transcript from file or existing processed data."""
        
        if transcript_file and os.path.exists(transcript_file):
            with open(transcript_file, 'r') as f:
                return f.read()
        
        # Look for existing processed video data
        possible_locations = [
            f"youtube_processed_videos/enterprise_videos/Educational_Content/{video_id}_results.json",
            f"gdrive_results/Educational_Content/{video_id}_real_results.json",
            f"grok4_processed_videos/General/{video_id}_grok4_results.json"
        ]
        
        for location in possible_locations:
            if os.path.exists(location):
                try:
                    with open(location, 'r') as f:
                        data = json.load(f)
                        # Extract transcript if available
                        if isinstance(data, dict):
                            return data.get('transcript', data.get('content', str(data)))
                except Exception as e:
                    print(f"Error reading {location}: {e}")
                    continue
        
        return None
    
    def _generate_implementation_files(self, video_id: str, action_result: Dict[str, Any]):
        """Generate specific implementation files for each action."""
        
        video_output_dir = self.output_dir / video_id
        video_output_dir.mkdir(exist_ok=True)
        
        for action in action_result.get("actions", []):
            action_type = action.get("type", "unknown")
            deliverables = action.get("deliverables", [])
            
            for deliverable in deliverables:
                self._create_deliverable_file(video_output_dir, action_type, deliverable, action)
    
    def _create_deliverable_file(self, output_dir: Path, action_type: str, deliverable: str, action: Dict[str, Any]):
        """Create a specific deliverable file."""
        
        filename = f"{action_type}_{deliverable}.md"
        filepath = output_dir / filename
        
        content = f"""# {action['title']}

## Description
{action['description']}

## Deliverable: {deliverable}

**Estimated Time:** {action['estimated_minutes']} minutes
**Priority:** {action['priority']}

## Implementation Notes
- Generated on: {datetime.now().isoformat()}
- Action Type: {action_type}
- Status: Ready for implementation

## Next Steps
1. Review the requirements
2. Begin implementation
3. Track progress
4. Mark as complete when finished

## Resources
- Video processing completed
- Direct action generation successful
- No complex coordination required

---
*Generated by Simple Video Workflow - Direct Action Generator*
"""
        
        with open(filepath, 'w') as f:
            f.write(content)
        
        print(f"Created deliverable: {filepath}")

def main():
    """CLI interface for simple video workflow."""
    
    if len(sys.argv) < 2:
        print("Usage: python simple_workflow.py <video_id> [transcript_file]")
        print("Example: python simple_workflow.py aircAruvnKk")
        sys.exit(1)
    
    video_id = sys.argv[1]
    transcript_file = sys.argv[2] if len(sys.argv) > 2 else None
    
    workflow = SimpleVideoWorkflow()
    result = workflow.process_video(video_id, transcript_file)
    
    if result.get("status") == "success":
        print(f"\n✅ SUCCESS: Processed {video_id}")
        print(f"Actions generated: {result['actions_generated']}")
        print(f"Estimated time: {result['estimated_time']} minutes")
        print(f"Category: {result['category']}")
        print(f"Output: {result['output_file']}")
    else:
        print(f"\n❌ ERROR: {result.get('error', 'Unknown error')}")
        sys.exit(1)

if __name__ == "__main__":
    main()